export enum RoutingConfig {
  login = 'login',
  registration = 'registration',
  home = '',
  tasks = 'tasks',
  notes = 'notes',
  files = 'files',
  alarms = 'alarms',
  videos = 'videos',
  bookmarks = 'bookmarks',
  create = 'create',
  catalogs = 'catalogs',
  toDo = 'to-do',
  settings = 'settings',
  deactivateSingle = 'deactivate-single',
  any = '**',
  task = 'task',
  alarm = 'alarm',
  byId = ':id',
  fb = 'fb',
  confirmEmail = 'confirm-email',
  changePassword = 'change-password',
  resetPassword = 'reset-password'
}
